# Site
title:   "Введение в программирование на Go"
url:     "http://golang-book.ru"
locale:  "ru"
baseurl: ""

# Source
source:      ./src
destination: ./build
plugins:     ./src/_plugins
layouts:     ./src/_layouts
data_source: ./src/_data

# Collections
collections:
  book:
    output: true
    permalink: '/:name.html'

# Build
permalink:   /:title.html
highlighter: null

# Assets
assets:
  js_compressor:  uglifier
  css_compressor: sass
  cache:          false
